### ISSUE TITLE
Do not hardcode connection URI

### ISSUE THREAD

**Issue by joroec** [joroec/virsnap#6]
The connection URI "qemu:///system" is hardcoded in pkg/virt/vm.go. We do not want to restrict usage to KVM users. Hence, we want a global command line flag to specify a custom connection URI for libvirt. The default value should be "qemu:///system".

**Comment by vwirth** [comment]
Would be happy to take this issue.

**Comment by obitech** [comment]
Makes sense. We can have it defined as a global flag with default value, then passed to `virt.ListMatchingVMs` I guess?

**Comment by vwirth** [comment]
Yes, I implemented it that way.
